// <auto-generated />
using System;
using DiskCommerce.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiskCommerce.Database.Migrations
{
    [DbContext(typeof(DiskEcommerceContext))]
    [Migration("20190127140255_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiskCommerce.Domain.Entities.BuyerAggregate.Buyer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.CashbackAggregate.OrderCashback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OrderCashbackValue")
                        .HasColumnName("CashbackValue")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<Guid?>("RelatedOrderId");

                    b.HasKey("Id");

                    b.HasIndex("RelatedOrderId");

                    b.ToTable("Cashback");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.CashbackAggregate.OrderCashbackItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CashbackPercentage")
                        .HasColumnName("CashbackPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CashbackValue")
                        .HasColumnName("CashbackValue")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<Guid?>("OrderCashbackId");

                    b.Property<Guid?>("RelatedOrderItemId");

                    b.HasKey("Id");

                    b.HasIndex("OrderCashbackId");

                    b.HasIndex("RelatedOrderItemId");

                    b.ToTable("OrderCashbackItem");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.Disk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Genre")
                        .HasColumnName("Genre")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Disks");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuyerId");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnName("OrderDate")
                        .HasColumnType("Datetime");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.OrderAggregate.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnName("UnitPrice")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Units")
                        .HasColumnName("Unit")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.CashbackAggregate.OrderCashback", b =>
                {
                    b.HasOne("DiskCommerce.Domain.Entities.OrderAggregate.Order", "RelatedOrder")
                        .WithMany()
                        .HasForeignKey("RelatedOrderId");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.CashbackAggregate.OrderCashbackItem", b =>
                {
                    b.HasOne("DiskCommerce.Domain.Entities.CashbackAggregate.OrderCashback")
                        .WithMany("OrderCashbacktems")
                        .HasForeignKey("OrderCashbackId");

                    b.HasOne("DiskCommerce.Domain.Entities.OrderAggregate.OrderItem", "RelatedOrderItem")
                        .WithMany()
                        .HasForeignKey("RelatedOrderItemId");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.OrderAggregate.Order", b =>
                {
                    b.HasOne("DiskCommerce.Domain.Entities.BuyerAggregate.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId");
                });

            modelBuilder.Entity("DiskCommerce.Domain.Entities.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("DiskCommerce.Domain.Entities.OrderAggregate.Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.OwnsOne("DiskCommerce.Domain.Entities.OrderAggregate.OrderedDisk", "OrderedDisk", b1 =>
                        {
                            b1.Property<Guid?>("OrderItemId");

                            b1.Property<Guid>("DiskId")
                                .HasColumnName("DiskID");

                            b1.Property<int>("Genre")
                                .HasColumnName("DiskGenre");

                            b1.Property<string>("Name")
                                .HasColumnName("DiskName");

                            b1.ToTable("OrderItem");

                            b1.HasOne("DiskCommerce.Domain.Entities.OrderAggregate.OrderItem")
                                .WithOne("OrderedDisk")
                                .HasForeignKey("DiskCommerce.Domain.Entities.OrderAggregate.OrderedDisk", "OrderItemId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
